### PR TITLE
Fix doc export build & improve readme

### PR DESCRIPTION
**Pull request by mDuo13**
- Fixes several case inconsistencies (only matters on case-sensitive filesystems, e.g. ext4 on Linux)
- replaces some deprecated/moved files
- better clarifies what repos you need to pull

### CODE REVIEW

**Comment by bhcrosslake** [comment]
might want to replace your use of the character ` with '. 
The ` character can't be parsed by dactyl/Prince and just becomes a black diamond.

**Comment by mDuo13** [comment]
which character?

**Comment by millerabel** [comment]
The back tick with the forward tick. Markdown uses back tick to open an inline code string. So @bhcrosslake’s msg was garbled. There may be a similar issue with dactyl. I don’t know where in the pull change this occurred.

**Comment by bhcrosslake** [comment]
Sorry @mDuo13, corrected my comment: replace the \` with '.

**Pull request merged**
